### ISSUE TITLE
Add Gnome Dynamic wallpapers

### ISSUE THREAD

**Issue by thblckjkr** [karmanyaahm/awesome-plasma5-dynamic-wallpapers#1]
I just found that there is a similar project but for Gnome. Maybe you could include the wallpapers that are there?

https://github.com/b1izzard-34/Dynamic-gnome-wallpapers

But, I think that it could be easier to just go to https://dynamicwallpaper.club and download the same wallpapers.

**Comment by karmanyaahm** [comment]
> I just found that there is a similar project but for Gnome. Maybe you could include the wallpapers that are there?

I think that existing would be helpful, but if someone who actively uses that app and uses gnome maintains it, it would be a better idea since they would be interacting with that project and the gnome aesthetic regularly.

> But, I think that it could be easier to just go to https://dynamicwallpaper.club and download the same wallpapers

Please correct me if I'm missing something, but I'm not sure how that would be relevant to this project since that website seems to be exclusively for Mac OS.
